export const DUMMY_KLAIM = [
  { id: 1, email_member: 'alice.johnson@email.com', email_staf: 'agus.budi@garuda.com', maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'CGK', bandara_tujuan: 'DPS', tanggal_penerbangan: '2025-01-10', flight_number: 'GA401', nomor_tiket: 'TKT20250101', kelas_kabin: 'Economy', pnr: 'ABC1001', status_penerimaan: 'Disetujui', timestamp: '2025-01-15 10:00:00' },
  { id: 2, email_member: 'alice.johnson@email.com', email_staf: null, maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'DPS', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-03-20', flight_number: 'GA402', nomor_tiket: 'TKT20250302', kelas_kabin: 'Business', pnr: 'ABC1002', status_penerimaan: 'Menunggu', timestamp: '2025-03-22 14:30:00' },
  { id: 3, email_member: 'budi.santoso@email.com', email_staf: 'siti.rahayu@garuda.com', maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'CGK', bandara_tujuan: 'SUB', tanggal_penerbangan: '2025-01-05', flight_number: 'GA501', nomor_tiket: 'TKT20250103', kelas_kabin: 'Economy', pnr: 'DEF1001', status_penerimaan: 'Ditolak', timestamp: '2025-01-08 09:00:00' },
  { id: 4, email_member: 'budi.santoso@email.com', email_staf: null, maskapai: 'JT', nama_maskapai: 'Lion Air', bandara_asal: 'CGK', bandara_tujuan: 'UPG', tanggal_penerbangan: '2025-04-01', flight_number: 'JT201', nomor_tiket: 'TKT20250404', kelas_kabin: 'Economy', pnr: 'DEF1002', status_penerimaan: 'Menunggu', timestamp: '2025-04-03 11:00:00' },
  { id: 5, email_member: 'carol.williams@email.com', email_staf: 'bambang.s@lionair.com', maskapai: 'JT', nama_maskapai: 'Lion Air', bandara_asal: 'SUB', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-02-14', flight_number: 'JT301', nomor_tiket: 'TKT20250205', kelas_kabin: 'Economy', pnr: 'GHI1001', status_penerimaan: 'Disetujui', timestamp: '2025-02-16 08:30:00' },
  { id: 6, email_member: 'david.brown@email.com', email_staf: 'dewi.indah@lionair.com', maskapai: 'JT', nama_maskapai: 'Lion Air', bandara_asal: 'SIN', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-02-28', flight_number: 'JT401', nomor_tiket: 'TKT20250206', kelas_kabin: 'First', pnr: 'JKL1001', status_penerimaan: 'Disetujui', timestamp: '2025-03-01 10:00:00' },
  { id: 7, email_member: 'eva.davis@email.com', email_staf: null, maskapai: 'QG', nama_maskapai: 'Citilink', bandara_asal: 'CGK', bandara_tujuan: 'BPN', tanggal_penerbangan: '2025-03-05', flight_number: 'QG101', nomor_tiket: 'TKT20250307', kelas_kabin: 'Economy', pnr: 'MNO1001', status_penerimaan: 'Menunggu', timestamp: '2025-03-07 13:00:00' },
  { id: 8, email_member: 'fajar.pratama@email.com', email_staf: 'erik.santoso@citilink.com', maskapai: 'QG', nama_maskapai: 'Citilink', bandara_asal: 'DPS', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-01-18', flight_number: 'QG201', nomor_tiket: 'TKT20250108', kelas_kabin: 'Economy', pnr: 'PQR1001', status_penerimaan: 'Disetujui', timestamp: '2025-01-20 15:00:00' },
  { id: 9, email_member: 'gita.lestari@email.com', email_staf: null, maskapai: 'ID', nama_maskapai: 'Batik Air', bandara_asal: 'CGK', bandara_tujuan: 'KNO', tanggal_penerbangan: '2025-04-10', flight_number: 'ID101', nomor_tiket: 'TKT20250409', kelas_kabin: 'Business', pnr: 'STU1001', status_penerimaan: 'Menunggu', timestamp: '2025-04-12 09:30:00' },
  { id: 10, email_member: 'hendra.wijaya@email.com', email_staf: 'galih.prabowo@batikair.com', maskapai: 'ID', nama_maskapai: 'Batik Air', bandara_asal: 'UPG', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-02-22', flight_number: 'ID201', nomor_tiket: 'TKT20250210', kelas_kabin: 'Economy', pnr: 'VWX1001', status_penerimaan: 'Disetujui', timestamp: '2025-02-24 11:00:00' },
  { id: 11, email_member: 'tika.pradana@email.com', email_staf: 'agus.budi@garuda.com', maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'CGK', bandara_tujuan: 'NRT', tanggal_penerbangan: '2025-01-25', flight_number: 'GA601', nomor_tiket: 'TKT20250111', kelas_kabin: 'Business', pnr: 'YZA1001', status_penerimaan: 'Disetujui', timestamp: '2025-01-27 16:00:00' },
  { id: 12, email_member: 'ujang.sopyan@email.com', email_staf: null, maskapai: 'QZ', nama_maskapai: 'AirAsia Indonesia', bandara_asal: 'KUL', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-03-15', flight_number: 'QZ101', nomor_tiket: 'TKT20250312', kelas_kabin: 'Economy', pnr: 'BCD1001', status_penerimaan: 'Menunggu', timestamp: '2025-03-17 08:00:00' },
  { id: 13, email_member: 'vera.chandra@email.com', email_staf: 'irfan.maulana@airasia.com', maskapai: 'QZ', nama_maskapai: 'AirAsia Indonesia', bandara_asal: 'CGK', bandara_tujuan: 'BKK', tanggal_penerbangan: '2025-02-08', flight_number: 'QZ201', nomor_tiket: 'TKT20250213', kelas_kabin: 'Economy', pnr: 'EFG1001', status_penerimaan: 'Disetujui', timestamp: '2025-02-10 14:00:00' },
  { id: 14, email_member: 'wibowo.purnomo@email.com', email_staf: 'jasmine.putri@airasia.com', maskapai: 'QZ', nama_maskapai: 'AirAsia Indonesia', bandara_asal: 'SIN', bandara_tujuan: 'DPS', tanggal_penerbangan: '2025-01-30', flight_number: 'QZ301', nomor_tiket: 'TKT20250114', kelas_kabin: 'First', pnr: 'HIJ1001', status_penerimaan: 'Ditolak', timestamp: '2025-02-01 10:30:00' },
  { id: 15, email_member: 'yuni.astuti@email.com', email_staf: null, maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'CGK', bandara_tujuan: 'SYD', tanggal_penerbangan: '2025-04-05', flight_number: 'GA701', nomor_tiket: 'TKT20250415', kelas_kabin: 'Economy', pnr: 'KLM1001', status_penerimaan: 'Menunggu', timestamp: '2025-04-07 12:00:00' },
  { id: 16, email_member: 'julia.sekarsari@email.com', email_staf: 'siti.rahayu@garuda.com', maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'JOG', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-03-12', flight_number: 'GA801', nomor_tiket: 'TKT20250316', kelas_kabin: 'Economy', pnr: 'NOP1001', status_penerimaan: 'Disetujui', timestamp: '2025-03-14 09:00:00' },
  { id: 17, email_member: 'kevin.lim@email.com', email_staf: null, maskapai: 'JT', nama_maskapai: 'Lion Air', bandara_asal: 'KUL', bandara_tujuan: 'SUB', tanggal_penerbangan: '2025-04-20', flight_number: 'JT501', nomor_tiket: 'TKT20250417', kelas_kabin: 'Business', pnr: 'QRS1001', status_penerimaan: 'Menunggu', timestamp: '2025-04-22 11:30:00' },
  { id: 18, email_member: 'linda.wulandari@email.com', email_staf: 'dewi.indah@lionair.com', maskapai: 'JT', nama_maskapai: 'Lion Air', bandara_asal: 'CGK', bandara_tujuan: 'PLM', tanggal_penerbangan: '2025-02-05', flight_number: 'JT601', nomor_tiket: 'TKT20250218', kelas_kabin: 'Economy', pnr: 'TUV1001', status_penerimaan: 'Disetujui', timestamp: '2025-02-07 13:30:00' },
  { id: 19, email_member: 'mario.setiawan@email.com', email_staf: null, maskapai: 'ID', nama_maskapai: 'Batik Air', bandara_asal: 'CGK', bandara_tujuan: 'DPS', tanggal_penerbangan: '2025-03-28', flight_number: 'ID301', nomor_tiket: 'TKT20250319', kelas_kabin: 'Economy', pnr: 'WXY1001', status_penerimaan: 'Menunggu', timestamp: '2025-03-30 10:00:00' },
  { id: 20, email_member: 'nina.anggraini@email.com', email_staf: 'fitri.nurhayati@citilink.com', maskapai: 'QG', nama_maskapai: 'Citilink', bandara_asal: 'CGK', bandara_tujuan: 'JOG', tanggal_penerbangan: '2025-01-14', flight_number: 'QG301', nomor_tiket: 'TKT20250120', kelas_kabin: 'Economy', pnr: 'ZAB1001', status_penerimaan: 'Ditolak', timestamp: '2025-01-16 15:00:00' },
  { id: 21, email_member: 'undyne@gmail.com', email_staf: 'agus.budi@garuda.com', maskapai: 'GA', nama_maskapai: 'Garuda Indonesia', bandara_asal: 'CGK', bandara_tujuan: 'DPS', tanggal_penerbangan: '2025-04-10', flight_number: 'GA888', nomor_tiket: 'TKT20250410', kelas_kabin: 'Economy', pnr: 'UND1001', status_penerimaan: 'Disetujui', timestamp: '2025-04-15 10:00:00' },
  { id: 22, email_member: 'undyne@gmail.com', email_staf: null, maskapai: 'JT', nama_maskapai: 'Lion Air', bandara_asal: 'SUB', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-04-20', flight_number: 'JT999', nomor_tiket: 'TKT20250420', kelas_kabin: 'Business', pnr: 'UND1002', status_penerimaan: 'Menunggu', timestamp: '2025-04-25 14:30:00' },
  { id: 23, email_member: 'undyne@gmail.com', email_staf: 'dewi.indah@lionair.com', maskapai: 'QG', nama_maskapai: 'Citilink', bandara_asal: 'KNO', bandara_tujuan: 'CGK', tanggal_penerbangan: '2025-03-01', flight_number: 'QG777', nomor_tiket: 'TKT20250301', kelas_kabin: 'Economy', pnr: 'UND1003', status_penerimaan: 'Ditolak', timestamp: '2025-03-05 09:00:00' },
];

// Member names lookup
export const MEMBER_NAMES: Record<string, string> = {
  'alice.johnson@email.com': 'Ms. Alice Johnson',
  'budi.santoso@email.com': 'Mr. Budi Santoso',
  'carol.williams@email.com': 'Mrs. Carol Williams',
  'david.brown@email.com': 'Mr. David Brown',
  'eva.davis@email.com': 'Ms. Eva Davis',
  'fajar.pratama@email.com': 'Mr. Fajar Pratama',
  'gita.lestari@email.com': 'Ms. Gita Lestari',
  'hendra.wijaya@email.com': 'Mr. Hendra Wijaya',
  'tika.pradana@email.com': 'Ms. Tika Pradana',
  'ujang.sopyan@email.com': 'Mr. Ujang Sopyan',
  'vera.chandra@email.com': 'Ms. Vera Chandra',
  'wibowo.purnomo@email.com': 'Mr. Wibowo Purnomo',
  'yuni.astuti@email.com': 'Ms. Yuni Astuti',
  'julia.sekarsari@email.com': 'Ms. Julia Sekarsari',
  'kevin.lim@email.com': 'Mr. Kevin Lim',
  'linda.wulandari@email.com': 'Ms. Linda Wulandari',
  'mario.setiawan@email.com': 'Mr. Mario Setiawan',
  'nina.anggraini@email.com': 'Ms. Nina Anggraini',
  'undyne@gmail.com': 'Ms. Undyne The Undying',
};
