export const DUMMY_TRANSFER = [
  { email_member_1: 'tika.pradana@email.com', nama_1: 'Ms. Tika Pradana', email_member_2: 'alice.johnson@email.com', nama_2: 'Ms. Alice Johnson', timestamp: '2025-02-01 10:00:00', jumlah: 2000, catatan: 'Transfer untuk teman' },
  { email_member_1: 'ujang.sopyan@email.com', nama_1: 'Mr. Ujang Sopyan', email_member_2: 'budi.santoso@email.com', nama_2: 'Mr. Budi Santoso', timestamp: '2025-02-05 11:30:00', jumlah: 1500, catatan: 'Berbagi miles' },
  { email_member_1: 'vera.chandra@email.com', nama_1: 'Ms. Vera Chandra', email_member_2: 'carol.williams@email.com', nama_2: 'Mrs. Carol Williams', timestamp: '2025-02-10 09:00:00', jumlah: 1000, catatan: 'Hadiah ulang tahun' },
  { email_member_1: 'wibowo.purnomo@email.com', nama_1: 'Mr. Wibowo Purnomo', email_member_2: 'david.brown@email.com', nama_2: 'Mr. David Brown', timestamp: '2025-02-15 14:00:00', jumlah: 3000, catatan: 'Kiriman keluarga' },
  { email_member_1: 'yuni.astuti@email.com', nama_1: 'Ms. Yuni Astuti', email_member_2: 'eva.davis@email.com', nama_2: 'Ms. Eva Davis', timestamp: '2025-02-20 16:00:00', jumlah: 500, catatan: null },
  { email_member_1: 'tika.pradana@email.com', nama_1: 'Ms. Tika Pradana', email_member_2: 'fajar.pratama@email.com', nama_2: 'Mr. Fajar Pratama', timestamp: '2025-03-01 08:30:00', jumlah: 2500, catatan: 'Bantu naik tier' },
  { email_member_1: 'julia.sekarsari@email.com', nama_1: 'Ms. Julia Sekarsari', email_member_2: 'gita.lestari@email.com', nama_2: 'Ms. Gita Lestari', timestamp: '2025-03-05 10:00:00', jumlah: 1200, catatan: null },
  { email_member_1: 'kevin.lim@email.com', nama_1: 'Mr. Kevin Lim', email_member_2: 'hendra.wijaya@email.com', nama_2: 'Mr. Hendra Wijaya', timestamp: '2025-03-10 13:00:00', jumlah: 800, catatan: 'Transfer lintas negara' },
  { email_member_1: 'linda.wulandari@email.com', nama_1: 'Ms. Linda Wulandari', email_member_2: 'indah.permata@email.com', nama_2: 'Ms. Indah Permata', timestamp: '2025-03-15 15:30:00', jumlah: 600, catatan: 'Terimakasih' },
  { email_member_1: 'mario.setiawan@email.com', nama_1: 'Mr. Mario Setiawan', email_member_2: 'joko.susilo@email.com', nama_2: 'Mr. Joko Susilo', timestamp: '2025-03-20 09:30:00', jumlah: 1800, catatan: null },
  { email_member_1: 'vera.chandra@email.com', nama_1: 'Ms. Vera Chandra', email_member_2: 'kartini.dewi@email.com', nama_2: 'Ms. Kartini Dewi', timestamp: '2025-04-01 11:00:00', jumlah: 750, catatan: 'Untuk perjalanan' },
  { email_member_1: 'wibowo.purnomo@email.com', nama_1: 'Mr. Wibowo Purnomo', email_member_2: 'lukman.hakim@email.com', nama_2: 'Mr. Lukman Hakim', timestamp: '2025-04-05 14:30:00', jumlah: 1000, catatan: null },
  { email_member_1: 'ujang.sopyan@email.com', nama_1: 'Mr. Ujang Sopyan', email_member_2: 'maya.sari@email.com', nama_2: 'Ms. Maya Sari', timestamp: '2025-04-10 16:00:00', jumlah: 2000, catatan: 'Kiriman rutin' },
  { email_member_1: 'yuni.astuti@email.com', nama_1: 'Ms. Yuni Astuti', email_member_2: 'nanda.putra@email.com', nama_2: 'Mr. Nanda Putra', timestamp: '2025-04-15 10:00:00', jumlah: 500, catatan: null },
  { email_member_1: 'tika.pradana@email.com', nama_1: 'Ms. Tika Pradana', email_member_2: 'olivia.tan@email.com', nama_2: 'Ms. Olivia Tan', timestamp: '2025-04-20 12:00:00', jumlah: 3000, catatan: 'Miles liburan bersama' },
];
